fragment BridgeQuoteFields on BridgeQuote {
  aggregator
  approval {
    address
    amount
  }
  estimate {
    amountToReceive
    executionDurationSeconds
    feeCosts
    feeCostsUsd
    fromAmountUsd
    gasCosts
    gasCostsUsd
    slippage
    toAmountUsd
  }
  id
  transaction {
    to
    from
    gasLimit
    gasPrice
    data
    value
    chainId
  }
}
