fragment NetworkFields on Network {
  decimals
  name
  networkCode
  networkName
  symbol
  identifiers {
    chainId
  }
  links {
    explorer
  }
  logo {
    png
    svg
  }
  regex {
    address
  }
}
