query GetAssetsForOrg(
  $limit: Int
  $offset: Int
  $currency: String
  $address: String
  $assetId: ID
) {
  assetsForOrganization(
    limit: $limit
    offset: $offset
    currency: $currency
    address: $address
    assetId: $assetId
  ) {
    address
    decimals
    id
    name
    networkCode
    symbol
    type
    config {
      mappedAssetId
    }
    networks {
      name
      networkCode
    }
    logo {
      png
      svg
    }
    price {
      price
    }
  }
}
