query GetAssetByMappedAssetIdAndNetworkCode($mappedAssetId: String, $networkCode: String) {
  assetByMappedAssetIdAndNetworkCode(mappedAssetId: $mappedAssetId, networkCode: $networkCode) {
    address
  }
}
