query GetAssetsForOrg($limit: Int, $offset: Int, $currency: String) {
  assetsForOrganization(limit: $limit, offset: $offset, currency: $currency) {
    id
    name
    networkCode
    networks {
      name
      networkCode
    }
    logo {
      png
      svg
    }
    symbol
  }
}