query GetNetworksForAsset($assetId: String) {
  networksForAssetByOrg(assetId: $assetId) {
    name
    networkCode
    logo {
      png
      svg
    }
    identifiers {
      chainId
    }
    symbol
  }
}
