query GetPaymentMethods($chainId: Int) {
  methodsForNetwork(chainId: $chainId) {
    name
    icon
    logo
    value
    flags {
      enabled
      memo
    }
    walletConnect {
      description
      chains
      app {
        ios
        android
      }
      mobile {
        native
        universal
      }
      desktop {
        native
      }
    }
  }
}